version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 294253399473.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t delivery_tracker:latest .
      - docker tag delivery_tracker:latest 294253399473.dkr.ecr.ap-south-1.amazonaws.com/delivery_tracker:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 294253399473.dkr.ecr.ap-south-1.amazonaws.com/delivery_tracker:latest
      - echo Push is completed
      - echo writing image definition file ...
      - printf '[{"name":"delivery_tracker_cluster","imageUri":"294253399473.dkr.ecr.ap-south-1.amazonaws.com/delivery_tracker"}]' > imagedefinitions.json


artifacts:
  files:
    - imagedefinitions.json